# Utiliser l'image officielle Papercups
FROM papercups/papercups:latest

# Variables d'environnement
ENV MIX_ENV=prod
ENV PORT=4000

# Exposer le port
EXPOSE 4000

# Commande de démarrage
CMD ["/entrypoint.sh", "run"]
